package com.github.ldaniels528.meansjs.nodejs.mongodb

import scala.scalajs.js
import scala.scalajs.js.annotation.ScalaJSDefined

/**
  * Index Options
  * @param w                  optional: The write concern (Default: null).
  * @param wtimeout           optional: The write concern timeout (Default: null).
  * @param j                  optional: Specify a journal write concern (Default: false).
  * @param unique             optional: Creates an unique index (Default: false).
  * @param sparse             optional: Creates a sparse index  (Default: false).
  * @param background         optional: Creates the index in the background, yielding whenever possible (Default: false).
  * @param dropDups           optional: A unique index cannot be created on a key that has pre-existing duplicate values. 
  *                           If you would like to create the index anyway keeping the first document the database indexes 
  *                           and deleting all subsequent documents that have duplicate value  (Default: false).
  * @param min                optional: For geospatial indexes set the lower bound for the co-ordinates (Default: null).
  * @param max                optional: For geospatial indexes set the high bound for the co-ordinates (Default: null).
  * @param v                  optional: Specify the format version of the indexes (Default: null).
  * @param expireAfterSeconds optional: Allows you to expire data on indexes applied to a data (MongoDB 2.2 or higher) (Default: null).
  * @param name               optional: Override the autogenerated index name (useful if the resulting name is larger than 128 bytes) (Default: null).
  */
@ScalaJSDefined
class IndexOptions(var w: js.Any = null,
                   var wtimeout: Integer = null,
                   var j: Boolean = false,
                   var unique: Boolean = false,
                   var sparse: Boolean = false,
                   var background: Boolean = false,
                   var dropDups: Boolean = false,
                   var min: Integer = null,
                   var max: Integer = null,
                   var v: Integer = null,
                   var expireAfterSeconds: Integer = null,
                   var name: Integer = null) extends js.Object 

