addSbtPlugin("org.scala-js"      % "sbt-scalajs"  % "0.6.28")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.0.1")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "2.5")
addSbtPlugin("com.github.gseitz" % "sbt-release"  % "1.0.11")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "1.1.1")
