addSbtPlugin("org.scala-js"      % "sbt-scalajs"   % "0.6.28")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"  % "2.0.4")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"  % "3.6")
addSbtPlugin("com.github.gseitz" % "sbt-release"   % "1.0.11")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"       % "2.0.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.6.0")
addSbtPlugin("com.dwijnand"      % "sbt-travisci"  % "1.2.0")
