package io.scalajs.nodejs.http

import scala.scalajs.js

@js.native
trait StatusCodes extends js.Object {
  val `100`: String = js.native
  val `101`: String = js.native
  val `102`: String = js.native
  val `103`: String = js.native
  val `200`: String = js.native
  val `201`: String = js.native
  val `202`: String = js.native
  val `203`: String = js.native
  val `204`: String = js.native
  val `205`: String = js.native
  val `206`: String = js.native
  val `207`: String = js.native
  val `208`: String = js.native
  val `226`: String = js.native
  val `300`: String = js.native
  val `301`: String = js.native
  val `302`: String = js.native
  val `303`: String = js.native
  val `304`: String = js.native
  val `305`: String = js.native
  val `307`: String = js.native
  val `308`: String = js.native
  val `400`: String = js.native
  val `401`: String = js.native
  val `402`: String = js.native
  val `403`: String = js.native
  val `404`: String = js.native
  val `405`: String = js.native
  val `406`: String = js.native
  val `407`: String = js.native
  val `408`: String = js.native
  val `409`: String = js.native
  val `410`: String = js.native
  val `411`: String = js.native
  val `412`: String = js.native
  val `413`: String = js.native
  val `414`: String = js.native
  val `415`: String = js.native
  val `416`: String = js.native
  val `417`: String = js.native
  val `418`: String = js.native
  val `421`: String = js.native
  val `422`: String = js.native
  val `423`: String = js.native
  val `424`: String = js.native
  val `425`: String = js.native
  val `426`: String = js.native
  val `428`: String = js.native
  val `429`: String = js.native
  val `431`: String = js.native
  val `451`: String = js.native
  val `500`: String = js.native
  val `501`: String = js.native
  val `502`: String = js.native
  val `503`: String = js.native
  val `504`: String = js.native
  val `505`: String = js.native
  val `506`: String = js.native
  val `507`: String = js.native
  val `508`: String = js.native
  val `509`: String = js.native
  val `510`: String = js.native
  val `511`: String = js.native
}
